<?php
include("tag_a.php")
?>
<?php
$name=$_POST["name"];
$ghymat=$_POST["ghymat"];
$id=$_POST["id"];
$imageurl="picture/".$image;
move_uploaded_file($_FILES["image"]["tmp_name"],$imageurl);
$a=mysqli_connect("localhost","root","","amir");
$b=mysqli_query($a,"INSERT INTO `mahsol`(`name`, `ghymat`, `id`, `img`) VALUES ('$name','$ghymat','$id','$imageurl');");
mysqli_close($a);
?>
<?php
if($b)
{
 ?>
 <script>
    location.replace("menu_mahsol.php");
 </script>   
 <?php
}else
echo("خطا");
?>
<?php
include("footer2.html");
?>