<?php
include("tag_a.html");
$name=$_POST["name"];
$ghymat=$_POST["ghymat"];
$id=$_POST["id"];
$a=mysqli_connect("localhost","root","","amir");
$b=mysqli_query($a,"INSERT INTO `mahsol`(`name`, `ghymat`, `id`) VALUES ('$name','$ghymat','$id');");
mysqli_close($a);
?>
<?php
if($b)
{
 ?>
 <script>
    location.replace("list_mahsol.php");
 </script>   
 <?php
}else
echo("خطا");
?>
<?php
include("footer2.html");
?>